### PR TITLE
Improved README file

### PR DESCRIPTION
**Pull request by yforster**
Most new sentences are taken from / inspired by our joint CoqPL '20 abstrac.

Changes:

- new introduction paragraph
- problems are separated into seeds, advanced problems, and target problems
- opam installation instructions already match upcoming opam package
- slight changes in the contribution paragraph, link to Andrej's structure guidelines

### CODE REVIEW

**Comment by yforster** [comment]
@mrhaandi already gave feedback. @DmxLarchey, do you want to have a look and tell us whether you're okay with the new README?

**Comment by DmxLarchey** [comment]
It seems `TRAKHTENBROT` is missing in the `README.md` but maybe it was already missing before ;-) @dominik-kirst would you like to update the file?

Otherwise I am happy with the restructuration along the lines of the CoqPL'20 abstract.

**Comment by yforster** [comment]
I'll add Trakhtenbrot tomorrow, no problem. Probably it was there and I accidentally dropped it

**Comment by DmxLarchey** [comment]
It seems I did not notice some mistakes in the `README.md`

- **good seed** is irrelevant now. I mean there is no reason to highlight `CM1_HALT` and `FMsetC_SAT` more than eg `MM2_HALTING`;
- My name is misspelled in the _Trakhtenbrot_ paper reference.

**Comment by yforster** [comment]
I'll fix both in the coqdoc PR, thanks!

**Pull request merged**
