### PR TITLE
Testing travis for the non-opam branch

### PR DESCRIPTION
**Pull request by yforster**
This should trigger a travis build for the wip branch under Coq 8.8.2

### CODE REVIEW

**Comment by DmxLarchey** [comment]
Hi guys,

Maybe that is a stupid question but how can I test you changes coming from a `forked` project ? Do I need to clone your forked project or can I work it out from the main project ?

Best,

D.

**Comment by DmxLarchey** [comment]
Hi Yannick,

Do we all need to setup Travis CI or is it enough that one of us sets it up ? I have the feeling that only one of us needs to test the whole project. Also, does working with Travis CI interferes in any way with either GitHub or Coq (like, we need special naming conventions for folders, special build process etc) ?

Best,

D.

**Comment by yforster** [comment]
> Maybe that is a stupid question but how can I test your changes coming from a `forked` project ? Do I need to clone your forked project or can I work it out from the main project ?

If you click on "command line instructions" next to "Merge pull request" Github tells you what to do :) You don't need a new directory, git can work with several remotes simultaneously.

> Do we all need to setup Travis CI or is it enough that one of us sets it up ? I have the feeling that only one of us needs to test the whole project. Also, does working with Travis CI interferes in any way with either GitHub or Coq (like, we need special naming conventions for folders, special build process etc) ?

I set it up, and it should work for all of us now. You have to be logged in to see it, but I think there should be a "All checks have passed feels" above the merge button, and to the right there is a "Show all checks" link. If you don't see it I have to check how to make it publicly visible.

> induction on was designed for extraction, not only for building terms and proofs. Once I can install Coq 8.10 with opam, I will review that part of the code. Typically the version with two parameters you propose packs the two arguments in a pair.

I accidentally did the travis changes on top of Andrej's fixes for 8.10. I don't have 8.10 yet, I'll investigate once it hits the opam repos.

**Comment by DmxLarchey** [comment]
> If you click on "command line instructions" next to "Merge pull request" Github tells you what to do :) You don't need a new directory, git can work with several remotes simultaneously.

Yep well but this creates a new branch and I cannot update your own fork ... I can only update the copy of your fork which will not be merged into this current PR.

**Comment by yforster** [comment]
In principle, I'm not sure how much it makes sense to edit a PR for maintainers.

But this PR has "allow edits from maintainers" set, so you can edit and push to this branch, because you're a maintainer of the library. You can either add `git@github.com:yforster/coq-library-undecidability.git` as a second remote and push there, or do a clean clone of the repo (from my fork), make commits and just push.

**Comment by yforster** [comment]
I've incorporated this without the fixes to compile under 8.10 into the `noopam` branch.

**Pull request closed without merging**
