### PR TITLE
Typo in the definition file PCP.v impacts naming schemes

### PR DESCRIPTION
**Pull request by DmxLarchey**
This is just an example of how correcting a typo impacts automatic naming schemes possibly far away in the code.

In `PCP.v`, cards are pairs of `string X` because `list` are understood as finite sets there. Of course they are synonymous but since `string` was defined, why not use it?

Well, this impacts introduced names where the default `l` is now replaced with `s`.

There is no need for this PR to be merged except if you agree that the typo should be corrected

### CODE REVIEW

**Comment by mrhaandi** [comment]
Actually, why `Definition string X := list X.` instead of `Notation`? Sometimes layers of definitions introduce difficulties.

**Comment by mrhaandi** [comment]
Also why `coq.8.15+rc1`? I'm currently working with the main `coq.8.15` release.

**Comment by DmxLarchey** [comment]
> Also why `coq.8.15+rc1`? I'm currently working with the main `coq.8.15` release.

Well this is the version in the current [`opam`](https://github.com/uds-psl/coq-library-undecidability/blob/coq-8.15/opam) file on the `coq-8.15` branch. I did change it for a test and forgot to revert it back.

**Comment by DmxLarchey** [comment]
> Actually, why `Definition string X := list X.` instead of `Notation`? Sometimes layers of definitions introduce difficulties.

I do not know. I did not change that. Indeed `Notation` could be better. What do you think @yforster?

**Comment by yforster** [comment]
> Also why `coq.8.15+rc1`? I'm currently working with the main `coq.8.15` release.

I have filed a PR updating to `coq-8.15` and fixed the installation instruction which were broken as discovered by Dominique.

> Actually, why Definition string X := list X. instead of Notation? Sometimes layers of definitions introduce difficulties.

Actually, this here immediately introduces a universe problem. So yes, both string and card should be a `Notation`

**Comment by DmxLarchey** [comment]
Ok I fix this as a `Notation`, then I wait for the updated `coq-8.15` and propose a merge when this works. I may have to revert back some names. I will try to remove the use of auto-generated names, if there is a quick fix.

**Comment by DmxLarchey** [comment]
@mrhaandi @yforster. Rebase done. I will merge tomorrow if no one objects.

**Pull request merged**
