### PR TITLE
Reduction from H10 to H10Z

### PR DESCRIPTION
**Pull request by yforster**
Nice and easy, I really enjoyed the library for `pos`!

### CODE REVIEW

**Comment by DmxLarchey** [comment]
Seems ok to me. I am gonna wait for CI and merge if ok.
What is the `dionat.` prefix ?

And yep I used the `pos` library a lot, so it is getting quite versatile
now ... I started developing it long ago, before I knew about Fin
and I am more used to its syntax. Ideally it should be merged with
Fin. I suppose it would not be difficult that they share the same
inductive type and pos is just an alias for Fin thought ...

**Comment by yforster** [comment]
Ah, dionat is an alias for the file where the original dp_eval function is 
defined. I think the original file was dio_single and I renamed the module 
locally so the name is more clear

**Comment by DmxLarchey** [comment]
I messed things up (a bit) ... instead of pushing to the branch of your fork, I did create
a new branch here called `yforster/H10Z`. Could you merge the changes in this PR ?

**Comment by yforster** [comment]
Ha, I remember doing something similar accidentally in the MetaCoq repo 
once. I'll try to merge :)

**Comment by yforster** [comment]
The merge worked. Waiting for CI now

**Comment by DmxLarchey** [comment]
Ok thanks for the merge ... could I have done it myself on your repo ?
In that case, do you know what I should have typed. I started with what is advised
above. Should I have cloned your own repo?

```
git fetch origin refs/pull/29/head
git checkout -b yforster/H10Z FETCH_HEAD
```

**Comment by yforster** [comment]
As a maintainer of the full repository, you have full push rights to branches that started a PR, yes.

It would be 

```
git remote add yforster git@github.com:yforster/coq-library-undecidability.git   
git pull --all
git checkout H10Z
```
Now you are on my branch and can do your work.

```git push```

then pushes back to my branch. I have my, yours, Dominik's and Andrej's fork of the repo as well as the main repo as different remotes on my local copy. This allows me to pull from all, merge between the branches and push to the main repo / my repo and branches on the other repos that have an open PR.

**Comment by DmxLarchey** [comment]
Thanks a lot !!! I wait for the CI. Will I be able to push in your H10Z after the merge or can I only do it while the PR is open ?

**Comment by DmxLarchey** [comment]
Also, I think I can erase the local copy of the H10Z branch called `yforster/H10Z`. Can I ?

**Comment by yforster** [comment]
Mh, interesting question. Never thought about it, so let's try :)

**Comment by yforster** [comment]
Yes, that's not needed anymore! (deleting branches is normally a non-issue, 
there's a restore functionality somewhere if I remember correctly correctly)

**Comment by DmxLarchey** [comment]
Push was not permitted anymore ;-)

```
dominique@napo:~/GitHub/coq-library-undecidability/theories/H10$ git commit -a
[H10Z 7fc585f] added a null comment to test if push if possible after a merge of the PR
 1 file changed, 1 insertion(+)
dominique@napo:~/GitHub/coq-library-undecidability/theories/H10$ git push
Décompte des objets: 5, fait.
Delta compression using up to 4 threads.
Compression des objets: 100% (5/5), fait.
Écriture des objets: 100% (5/5), 483 bytes | 0 bytes/s, fait.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To git@github.com:yforster/coq-library-undecidability.git
 ! [remote rejected] H10Z -> H10Z (permission denied)
error: impossible de pousser des références vers 'git@github.com:yforster/coq-library-undecidability.git'
```

**Comment by DmxLarchey** [comment]
Well I know that you cannot really erase over `git` but it is just to avoid polluting the branches namespace

**Pull request merged**
