### PR TITLE
CI for Coq 8.16

### PR DESCRIPTION
**Pull request by yforster**

### CODE REVIEW

**Comment by yforster** [comment]
Oh no, this is probably going to fail until the opam package for MetaCoq is merged (https://github.com/coq/opam-coq-archive/pull/2288#issuecomment-1239201703), which in turn relies on a new release of MetaCoq (https://github.com/MetaCoq/metacoq/pull/748)

**Comment by mrhaandi** [comment]
> Oh no, this is probably going to fail until the opam package for MetaCoq is merged ([coq/opam-coq-archive#2288 (comment)](https://github.com/coq/opam-coq-archive/pull/2288#issuecomment-1239201703)), which in turn relies on a new release of MetaCoq ([MetaCoq/metacoq#748](https://github.com/MetaCoq/metacoq/pull/748))

Now that the package is released, what is the state of this PR?

**Comment by yforster** [comment]
https://github.com/coq/opam-coq-archive/pull/2370

**Comment by mrhaandi** [comment]
@yforster Note that `smpl` will not be necessary anymore with https://github.com/uds-psl/coq-library-undecidability/pull/176, which is ready.

**Pull request merged**
