### PR TITLE
replace prodLists with list_prod from stdlib

### PR DESCRIPTION
**Pull request by haansn08**

### CODE REVIEW

**Comment by DmxLarchey** [comment]
Hi @haansn08. Is this a _systematic_ replacement of `prodList` by `list_prod` from StdLib?

**Comment by DmxLarchey** [comment]
> @DmxLarchey Not sure what you mean by systematic, but I made sure the library still compiles.

I mean that there is no occurrence of `prodList` anymore after the resulting update? Or is this just a punctual change in two files ?

**Comment by haansn08** [comment]
There are no other occurrences of `prodList`. I now also removed the Lemma `prod_nil` which also seems to be unused.

**Comment by DmxLarchey** [comment]
Considering it is a systematic replacement with an equivalent tool from the standard library, I would likely ok the change. @yforster and @mrhaandi do you agree with merging this ?

**Comment by DmxLarchey** [comment]
> There are no other occurrences of `prodList`. I now also removed the Lemma `prod_nil` which also seems to be unused.

**Comment by DmxLarchey** [comment]
> > There are no other occurrences of `prodList`. I now also removed the Lemma `prod_nil` which also seems to be unused.

If `prod_nil` isn't already in the StdLib, maybe it could be left.

**Comment by mrhaandi** [comment]
> > > There are no other occurrences of `prodList`. I now also removed the Lemma `prod_nil` which also seems to be unused.
> 
> If `prod_nil` isn't already in the StdLib, maybe it could be left.

`prod_nil` refers to the removed `prodList` and should be removed as well. Since the equivalent statement for `list_prod` is not necessary, there is no need to formulate it.

**Review by mrhaandi — APPROVED** [review]

**Comment by mrhaandi** [comment]
I approve the proposed changes. @yforster it would be good to have a proper CI run before merge; what is the status of https://github.com/uds-psl/coq-library-undecidability/pull/171?

**Comment by mrhaandi** [comment]
To be on the safe side (without currently functioning ci), I have compiled the PR locally without issues.

**Review by DmxLarchey — APPROVED** [review]

**Pull request merged**
