### PR TITLE
Proof of decidable equality for Mu-recursive algorithms

### PR DESCRIPTION
**Pull request by DmxLarchey**
The proof is based on component-wise decision for vectors equality.

- @dominik-kirst, @JoJoDeveloping does this proof simplify yours? It does not use `Equations` btw.
- @mrhaandi, it seems @yforster already filed some structure in the `MuRec` subdir, at least in the `coq-8.15` branch. I did not notice this before. Is this Ok with you ?

### CODE REVIEW

**Comment by mrhaandi** [comment]
> it seems @yforster already filed some structure in the `MuRec` subdir, at least in the `coq-8.15` branch. I did not notice this before. Is this Ok with you ?

Mostly yes (also in `8.16`). The files were just dumped into `/MuRec/Util/` and could be cleaned up slightly. For example `RA_UNIV_HALT_undec.v` does not belong to Util and some redundancies with `_andrej.v` files can be cleaned up.

However, if you have little time, Yannick's quick refactoring is already ok.

**Comment by JoJoDeveloping** [comment]
Yes, my proof is similar, also using UIP on nat. It defines a custom inversion principle. See https://gist.github.com/JoJoDeveloping/63a545b185100952fa48fa480c96c312 (also including the enumerator)

**Comment by DmxLarchey** [comment]
@mrhaandi Migrated to `coq-8.16`.

**Comment by DmxLarchey** [comment]
> Yes, my proof is similar, also using UIP on nat. It defines a custom inversion principle. See https://gist.github.com/JoJoDeveloping/63a545b185100952fa48fa480c96c312 (also including the enumerator)

Yep, designing a custom inversion predicate was the way I did inversion back in my ITP'17 paper on µ-recursive algos, see [Typing total recursive functions in Coq page 13](https://members.loria.fr/DLarchey/files/papers/ITP_2017_paper_16.pdf).

**Comment by yforster** [comment]
Happy to merge this right after #176, or is there reason to wait @DmxLarchey?

**Pull request merged**
