### PR TITLE
Change license from CeCILL v2 to MPL-2.0 (more permissive)

### PR DESCRIPTION
**Pull request by DmxLarchey**
Following the issue #207, I propose this relicensing PR.

No functional change at all here since only _at most one line of comment_ is updated for each `.v` file. 

However, please check that the two added files `MPL-2.0_LICENSE.txt` and `scripts/relicense_to_MPL.txt` are properly placed. 

Possibly we could consider a `licenses` subdir? Also about the new `scripts` subdir:
- is it properly placed? named?
- it is here only to remind what was done.

The `CeCILL_LICENSE.txt` file is kept for the moment but could be pruned easily in a later update.

### CODE REVIEW

**Comment by Zimmi48** [comment]
Usually, when a project is not dual-licensed, it is recommended to keep a single license file and to name it `LICENSE`. This helps both humans and automated tools understand more quickly what the project license is.

For instance, GitHub will automatically display the license it detected in this summary of the repository:

image

Note that you should also update the `license` field in the `opam` file.

**Comment by yforster** [comment]
Maybe we leave the commit as is, and put a commit on top that removes the CECILL file and the `scripts` subdir? That way the information is not lost because it strays part of the git tree, but it also stays around too prominently

**Comment by DmxLarchey** [comment]
@Zimmi48 thx for the `opam` tip ...

**Comment by DmxLarchey** [comment]
Ok so I squash merge this PR and then submit another one that removes the reference to the former CeCILL license and the `scripts` subdir.

**Review by mrhaandi — APPROVED** [review]

**Pull request merged**
